# Generated by Django 4.0 on 2021-12-14 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(-5)])),
                ('parking_space_number', models.IntegerField(unique=True)),
                ('booking_start_time', models.DateTimeField(auto_now_add=True)),
                ('booking_end_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
