# Generated by Django 4.0 on 2021-12-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_time', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktime',
            old_name='parking_space_number',
            new_name='parking_space_id',
        ),
    ]
