# Generated by Django 4.0 on 2021-12-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_time', '0002_rename_parking_space_number_booktime_parking_space_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktime',
            name='owner',
        ),
    ]
