# Generated by Django 4.0 on 2021-12-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('booking_time', '0003_remove_booktime_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveBookTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_time.booktime')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
