# Generated by Django 4.0 on 2021-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_time', '0006_alter_reservebooktime_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktime',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='reservebooktime',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='booktime',
            name='booking_end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booktime',
            name='booking_start_time',
            field=models.DateField(),
        ),
    ]
