# Generated by Django 4.0 on 2021-12-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_time', '0008_alter_booktime_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservebooktime',
            name='book_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_time.booktime', unique=True),
        ),
    ]
